services:
  sphinx:
    build:
      context: .docker/sphinx
    volumes:
      - ./:/app

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./_build:/usr/share/nginx/html
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - sphinx
