services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:80"
    container_name: rtd-docs-libresign
  nginx:
    image: nginx:latest
    volumes:      
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    ports:
      - "8005:80"
