services:
  sphinx:
    build:
      context: .docker/sphinx
    volumes:
      - ./docs:/app/docs
      - ./volumes/html:/app/_build
      - ./volumes/cache:/pipcache
    environment:
      - PIP_CACHE_DIR=/pipcache

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./volumes/html:/usr/share/nginx/html
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - sphinx
